### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [fltk-rs/fluid#2]
```
cargo install fltk-fluid
    Updating crates.io index
     Ignored package `fltk-fluid v0.1.3` is already installed, use --force to override
``` 

``` 
fltk-fluid              
zsh: segmentation fault  fltk-fluid
``` 

On Mac OS Big Sur 11.4 on
MacBook Pro (16-inch, 2019)

**Comment by MoAlyousef** [comment]
I’ll pull the latest version if FLTK which has some fix for MacOS related to crashes because of some timer issues. Would you have a backtrace of the segfault?

**Comment by andrewdavidmackenzie** [comment]
No backtrace displayed beyond what I show above.
I tried RUST_BACKTRACE but no joy.
Am trying to gdb it, but run into signing problems....

**Comment by MoAlyousef** [comment]
Can you try with version 0.1.4?

**Comment by andrewdavidmackenzie** [comment]
Yep, 0.1.4 works just fine.

**Comment by andrewdavidmackenzie** [comment]
Closed how?

If you install latest, it crashes....

**Comment by MoAlyousef** [comment]
Version 0.1.4 was published on crates.io. It’s the current latest.

**Comment by andrewdavidmackenzie** [comment]
OK, I get it, so when I installed initially and reported I got a previous version, and you pushed out 0.1.4 in the last 24h with a fix. OK. thanks.

**Comment by xx-zhang** [comment]
@MoAlyousef hi, whats' this error to fix;  i have `git --recursive` and  also not install well . 

```
root@6d2d50d81e3e:~# cargo install fltk-fluid@0.1.9
    Updating `tuna` index
  Installing fltk-fluid v0.1.9
   Compiling cc v1.0.79
   Compiling cmake v0.1.49
   Compiling fltk-fluid v0.1.9
error: failed to run custom build command for `fltk-fluid v0.1.9`

Caused by:
  process didn't exit successfully: `/tmp/cargo-install5twcHJ/release/build/fltk-fluid-8c6471075dbef6a2/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NotPresent', /root/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/fltk-fluid-0.1.9/build.rs:6:59
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: failed to compile `fltk-fluid v0.1.9`, intermediate artifacts can be found at `/tmp/cargo-install5twcHJ`
root@6d2d50d81e3e:~# RUST_BACKTRACE=1 cargo install fltk-fluid@0.1.9
    Updating `tuna` index
  Installing fltk-fluid v0.1.9
   Compiling cc v1.0.79
   Compiling cmake v0.1.49
   Compiling fltk-fluid v0.1.9
error: failed to run custom build command for `fltk-fluid v0.1.9`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installalU3yC/release/build/fltk-fluid-8c6471075dbef6a2/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NotPresent', /root/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/fltk-fluid-0.1.9/build.rs:6:59
  stack backtrace:
     0: rust_begin_unwind
               at /build/rustc-JxKrFO/rustc-1.65.0+dfsg0ubuntu1~llvm2/library/std/src/panicking.rs:584:5
     1: core::panicking::panic_fmt
               at /build/rustc-JxKrFO/rustc-1.65.0+dfsg0ubuntu1~llvm2/library/core/src/panicking.rs:142:14
     2: core::result::unwrap_failed
               at /build/rustc-JxKrFO/rustc-1.65.0+dfsg0ubuntu1~llvm2/library/core/src/result.rs:1785:5
     3: core::result::Result<T,E>::unwrap
     4: build_script_build::main
     5: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: failed to compile `fltk-fluid v0.1.9`, intermediate artifacts can be found at `/tmp/cargo-installalU3yC`
```

**Comment by MoAlyousef** [comment]
Hi
This crate builds fluid from source, that means it requires cmake and a C++ compiler to be installed.
